### ISSUE TITLE
Questions on CTI

### ISSUE THREAD

**Issue by r01ex-ai** [Betswish/MIRAGE#1]
What happens when generated response without context has less token length than the one generated with context when calculating CTI. Couldn't find it in this repo.
Also, is there a result or a reason not to perform CTI with original generated prefix like it is done with CCI?

**Comment by Betswish** [comment]
Hi @r01ex-ai,

There is a misunderstanding of our CTI process. 
The CTI scores are calculated based on the "already generated prefix" of each token and only focus on the distribution of the next token.

For instance:
***
Q: Who is the author of the MIRAGE paper?
C: Qiorios and Gsarti are two of the authors of that paper!
LLM response: The authors are Qiorios and Gsarti.

CTI("The") = KL-divergence(distribution(next_token| Q + C), distribution(next_token | Q))
CTI("authors") = KL-divergence(distri(next_token | Q + C + **"The"**), distri(next_token | Q + **"The"**))
...
CTI("Qiorios") = KL-divergence(distri(next_token | Q + C + **"The authors are"**), distri(next_token | Q + **"The authors are"**))
...
CTI("Gsarti") = KL-divergence(distri(next_token | Q + C + **"The authors are Qiorios and"**), distri(next_token | Q + **"The authors are Qiorios and"**))
***

As you can imagine, the CTI scores for the LLM-already-knew tokens should be low, like "The", "authors", "and" ...
However, the scores will be relatively high if the knowledge model doesn't know before it sees the context, such as "Qiorios" and "Gsarti". 
This supports our CTI purpose - detecting the contextual-sensitive tokens in the LLM response.

**Comment by r01ex-ai** [comment]
Oh this makes so much more sense. Thanks for the quick reply
