### ISSUE TITLE
Could you share the MIRAGE-reproduce repo?

### ISSUE THREAD

**Issue by DingQiang2018** [Betswish/MIRAGE#2]
Hi authors,

I'm a student interested in your paper. However, the [repository](https://github.com/Betswish/MIRAGE-reproduce) that reproduces the results of the paper is not publicly available. Could you share it?

**Comment by Betswish** [comment]
Hi @DingQiang2018, the reproducing repository is being processed at the final stage and will be released in two weeks!

**Comment by DingQiang2018** [comment]
Thanks a lot!

**Comment by Betswish** [comment]
Hi @DingQiang2018 , the GitHub repository for reproducing the results is public now! https://github.com/Betswish/MIRAGE-reproduce
